variables:
  MAKEFLAGS: "-j10"
  VERBOSE: 1
  PACMAN_OPTS: --needed --noconfirm

cache:
  key: pkgs-v1
  paths:
    # For some reason Gitlab CI only supports storing cache/artifacts in a path relative to the build directory
    - /var/cache/pacman/pkg/

.manjaro-test:
  image: manjarolinux/build@sha256:f33bba9814b3ebe30616c961b87afc144710dbcc1066ec6f4c83ec23dc1bd719
  before_script:
    - cp  $CI_PROJECT_DIR/makepkg.conf /etc/makepkg.conf
    - pacman-key --init 
    - pacman-key --populate
    - pacman-key --recv-keys "536487F1470D7187" --keyserver hkps://keyserver.ubuntu.com
    - export GPG_TTY=$(tty)
    - gpg -v --batch --import <(echo "$GPG_PRIVATE_KEY")
    - pacman-key --import-trustdb ~/.gnupg/
    - pacman-mirrors --geoip
    - pacman -Sy
    - pacman -Syu $PACMAN_OPTS
      base-devel git clang lld git-lfs openssh rsync lsb-release
    - pacman -Syu $PACMAN_OPTS
    - useradd builder
    - su builder
    - export set LLVM=1
    - export set LLVM_IAS=1
    - export set CC='clang'
    - export set CXX='clang++'
    - export set HOSTCC='clang'
    - export set HOSTCXX='clang++'
    - export set LD='ld.lld'

manjaro:
  extends: .manjaro-test
  script:
    - git clone --depth 1 --single-branch https://gitlab.com/phoepsilonix/Manjaro-jp/
    - cd Manjaro-jp/Packages/linux515
    - 7z --version
    - makepkg -sCc
    - mkdir -p ~/binaries
    - 7z a -v100m ~/binaries/linux515.7z *.zst src/linux-5.15/certs/signing_key.*
  artifacts:
    paths:
       - ~/binaries/
